### ISSUE TITLE
GroupItemField with attributes

### ISSUE THREAD

**Issue by dennisusdev** [eko/FeedBundle#42]
Hi, first thanks for this very useful bundle.  I figured out how to add attributes to a custom ItemField, what I need to do now is take it a step further and nest other tags beneath that.  For example, i can get my ```<foo bar="whatever">``` tag like so:

```
$feed->addItemField(new ItemField('foo', 'getBar', array(
    'attribute' => true,
    'attribute_name' => 'bar',
));
```

But what I ultimately need is this, and don't see a way yet to add attributes to GroupItemFields:

```
<foo bar="whatever">
  <baz>Something Else</baz>
  <bop>Another Thing</bop>
  <boop>And Another</boop>
</foo>
```

One suggestion would be an option to pass either a string or an instance of ItemField as the first parameter of GroupItemField::construct().  In the case of a string, the current behavior remains (a simple tag like ```<string>``` is used for the parent tag), but if an ItemField object is passed, then IT gets used as the parent tag.  This would solve my problem, and potentially others?

So in this case, the code would look something like:

```
$parent = new ItemField('foo', 'getBar', array(
    'attribute' => true,
    'attribute_name' => 'bar',
));

$feed->addGroupItemField($parent, array(
    new ItemField('baz', 'getBaz'),
    new ItemField('bop', 'getBop'),
    new ItemField('boop', 'getBoop'),
));
```

Thoughts?

**Comment by eko** [comment]
Hi @dennisusdev,

Do you really need the attribute value to be obtained from an entity method? Or something like this (adding an attributes array) could works for you:

```php
$feed->addGroupItemField('foo', array(
    new ItemField('baz', 'getBaz'),
    new ItemField('bop', 'getBop'),
    new ItemField('boop', 'getBoop'),
), array('bar' => 'whatever');
```

This will produce the same result as you need:

```xml
<foo bar="whatever">
  <baz>Something Else</baz>
  <bop>Another Thing</bop>
  <boop>And Another</boop>
</foo>
```

Only difference is that this is a static value. Let me know.

Thank you!

**Comment by eko** [comment]
Alright @dennisusdev,

So I've added something to check if the given value is corresponding to a method into the entity. If yes, we retrieve the returned value from the method, else, the string value is used.

So for now, you can do the following for instance:

```php
$feed->addGroupItemField('foo', array(
        new ItemField('baz', 'getBaz'),
        new ItemField('bop', 'getBop'),
        new ItemField('boop', 'getBoop'),
    ), array('getAttributeKey' => 'getAttributeValue')
);
```

and add these methods into your entity:

```php
public function getAttributeKey()
{
    return 'bar';
}

public function getAttributeValue()
{
    return 'whatever';
}
```

This will produce the same result as you need and you can retrieve custom data from your entity:

<foo bar="whatever">
  <baz>Something Else</baz>
  <bop>Another Thing</bop>
  <boop>And Another</boop>
</foo>
```

Can you please close this issue if it's ok for you?

Hope it helps.

**Comment by dennisusdev** [comment]
This works great.  Thanks very much!
