### ISSUE TITLE
Bug in attribute value assignment

### ISSUE THREAD

**Issue by dennisusdev** [eko/FeedBundle#44]
I believe there is a bug in Formatter/Formatter.php - on line 300, where the value is supposed to be set for an attribute,  $item->getFeedItemLink() is being used in place of the value:

```php
$element->setAttribute($field->get('attribute_name'), $item->getFeedItemLink());
```

should be

```php
$element->setAttribute($field->get('attribute_name'), $value); 
```

In case I'm misunderstanding how it's supposed to work, I am setting up the item with attributes like this:

```php
$feed->addItemField(new ItemField('media:thumbnail', 'getFeedImageThumbnail', 
    array('attribute' => true,'attribute_name' => 'url')
));
```

and expect an xml element like:

```xml
<media:thumbnail url="http://example.com/image.jpg"/>
```

Thanks again for your work here

**Comment by eko** [comment]
Hi @dennisusdev,

Thank you again, that's right, the value must be sent to the attribute here ;)

It's fixed!
