### ISSUE TITLE
Add content in an Item, without calling a method in the Entity.

### ISSUE THREAD

**Issue by ludovicpages** [eko/FeedBundle#46]
Hi.
I would like to know if there is any way to add some content in an Item, without calling a method in the Entity.
On my code, each entity Article as a "modules" property, which is an Array Collection of differents set of other entities ( in order for the user to be able to build flexible content).

Basically, i would like to add content in an Item, the same way i can add content to the Channel with the following method : 
$feed->addChannelField(new ChannelField('custom_name', 'custom_value'));

Thanks for reader me.

Ludo

**Comment by eko** [comment]
Hi @ludovicpages,

Sorry for my response delay.

Of course, it's possible.

Here is the way to achieve this:

```php
<?php
$feed->addItemField(new ItemField('custom_name', 'custom_value'));
```

This way, all of your items will have a custom_name node with a custom_value.

Closing this issue.
