### ISSUE TITLE
Having problem adding RSS feeds to Entity

### ISSUE THREAD

**Issue by shairyar** [eko/FeedBundle#52]
Hi,

I am trying to save the RSS feeds being fetched to my database, following the instructions this is the code inside my controller

<pre>
       $reader = $this->get('eko_feed.feed.reader');       
        $items = $reader->load('http://rss.indeed.com/rss?q=Singapore')->populate('AppBundle\Entity\Rss');
</pre>

This is my Rss Entity

<pre>
<?php
namespace AppBundle\Entity;

use Eko\FeedBundle\Item\Reader\ItemInterface;

class Rss implements ItemInterface
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    protected $title;

    /**
     * @var string
     */
    protected $description;

    /**
     * @var string
     */
    protected $link;

    /**
     * @var \DateTime
     */
    protected $date;

    /**
     * @var \DateTime
     */
    private $publicationDate;

    /**
     * @var string
     */
    private $feedItemTitle;

    /**
     * @var string
     */
    private $feedItemDescription;

    /**
     * @var string
     */
    private $feedItemLink;

    /**
     * @var \DateTime
     */
    private $feedItemPubDate;
    /**
     * Returns a title
     *
     * @return string
     */
    public function setFeedItemTitle($title)
    {
        $this->title = $title;
    }

    /**
     * Returns a description or content
     *
     * @return string
     */
    public function setFeedItemDescription($description)
    {
        $this->description = $description;
    }

    /**
     * Returns item link
     *
     * @return string
     */
    public function setFeedItemLink($link)
    {
        $this->link = $link;
    }

    /**
     * Returns publication date
     *
     * @return \DateTime
     */
    public function setFeedItemPubDate(\DateTime $date)
    {
        $this->date = $date;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Get link
     *
     * @return string
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * Get publication date
     *
     * @return \DateTime
     */
    public function getPublicationDate()
    {
        return $this->date;
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Rss
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Rss
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Set link
     *
     * @param string $link
     * @return Rss
     */
    public function setLink($link)
    {
        $this->link = $link;

        return $this;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     * @return Rss
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime 
     */
    public function getDate()
    {
        return $this->date;
    }
    

    /**
     * Set publicationDate
     *
     * @param \DateTime $publicationDate
     * @return Rss
     */
    public function setPublicationDate($publicationDate)
    {
        $this->publicationDate = $publicationDate;

        return $this;
    }

    /**
     * Get feedItemTitle
     *
     * @return string 
     */
    public function getFeedItemTitle()
    {
        return $this->feedItemTitle;
    }

    /**
     * Get feedItemDescription
     *
     * @return string 
     */
    public function getFeedItemDescription()
    {
        return $this->feedItemDescription;
    }

    /**
     * Get feedItemLink
     *
     * @return string 
     */
    public function getFeedItemLink()
    {
        return $this->feedItemLink;
    }

    /**
     * Get feedItemPubDate
     *
     * @return \DateTime 
     */
    public function getFeedItemPubDate()
    {
        return $this->feedItemPubDate;
    }
}

</pre>

When i run the action the error i get is as following and i don't understand why. What am i doing wrong?
<pre>
Error: Call to a member function hydrate() on null
</pre>

**Comment by eko** [comment]
Hi @shairyar,

This is because you have to use an hydrator class (or the following default hydrator class: https://github.com/eko/FeedBundle/blob/master/Hydrator/DefaultHydrator.php).

Your code should be:

```php
$reader = $this->get('eko_feed.feed.reader');
$reader->setHydrator(new DefaultHydrator());

$items = $reader->load('http://rss.indeed.com/rss?q=Singapore')->populate('AppBundle\Entity\Rss');
```

Hope it helps.

**Comment by shairyar** [comment]
Hi @eko 

Thanks, that solved the problem, how do i persist it to the database then

I tried the following
<pre>
$reader = $this->get('eko_feed.feed.reader');
        $reader->setHydrator(new DefaultHydrator());
        $items = $reader->load('http://rss.indeed.com/rss?q=Singapore')->populate('AppBundle\Entity\Rss');
        dump($items);
        $em = $this->getDoctrine()->getManager();
        $em->persist($items);
        $em->flush();
        return $this->render('default/index.html.twig');
</pre>

but that gives me an error of 

<pre>
EntityManager#persist() expects parameter 1 to be an entity object, array given.
</pre>

**Comment by eko** [comment]
@shairyar,

You have to persist item per item:

```php
$reader = $this->get('eko_feed.feed.reader');
$reader->setHydrator(new DefaultHydrator());
$items = $reader->load('http://rss.indeed.com/rss?q=Singapore')->populate('AppBundle\Entity\Rss');

$em = $this->getDoctrine()->getManager();

foreach ($items as $item) {
    $em->persist($item);
}

$em->flush();

return $this->render('default/index.html.twig');
```

Can you please close this issue?

Thank you

**Comment by shairyar** [comment]
Just one last question, is it possible to fetch feeds after the specific date? or that needs to be handled by me in my code logic?

**Comment by eko** [comment]
This is not possible through this bundle, you have to develop this logic.
