### ISSUE TITLE
FeedDumpService instance error

### ISSUE THREAD

**Issue by stokjes** [eko/FeedBundle#56]
When executing the command which uses the FeedDumpService the following error occurs:

`  [Symfony\Component\Debug\Exception\ContextErrorException]
  Catchable Fatal Error: Argument 2 passed to Eko\FeedBundle\Service\FeedDumpService::__construct() must be an instance of Doctrine\ORM\EntityManager, instance of Ehealth\DoctrineEncryptionBundle\ORM\EntityManagerDecorator given, calle
  d in /run/shm/ehealthsoa/cache/dev/appDevDebugProjectContainer.php on line 2535 and defined`

This error can be resolved by changing the typehint for Doctrine to: `EntityManagerInterface` in the `FeedDumpService::__constructor();`

Hope this helps.

**Comment by eko** [comment]
Hi @stokjes,

Thank you for your feedback, I just fixed that and `FeedDumpService` now asks for an `EntityManagerInterface`.

I've tagged it into a new `1.2.8` tag.
