### ISSUE TITLE
custom fields

### ISSUE THREAD

**Issue by grekpg** [eko/FeedBundle#62]
I need publish information in atom xml format, 
this i need 
https://developers.facebook.com/resources/dpa_product_catalog_sample_feed_atom.xml

can i add extra fields to atom feed ?

**Comment by eko** [comment]
Hi @grekpg,

Of course, you can refer too the following documentation part for creating custom fields: https://github.com/eko/FeedBundle#add-some-custom-items-fields

These custom fields works both for RSS and ATOM formats.

I close this issue, feel free to reopen if you encounter any issue during implementation.

Thank you
