### ISSUE TITLE
Tag a new release version

### ISSUE THREAD

**Issue by franmomu** [eko/FeedBundle#73]
Hi, would it be possible tag a new version whenever you can to get rid of the deprecations notices? Thanks

**Comment by eko** [comment]
Hi @franmomu,

Sorry for the delay but I announce that the bundle is now compatible with Symfony 5.0, see the following PR: https://github.com/eko/FeedBundle/pull/74

Tag `2.0.0` has been released.

Closing this issue for now.

Thank  you
